openapi: 3.0.0
info:
  title: File Upload and Example API
  version: 1.0.0
  description: API for uploading files to Azure Blob Storage and additional GET/POST operations.

paths:
  /upload:
    post:
      summary: Upload a file to Azure Blob Storage
      operationId: uploadFileToAzure
      uploadType: azure-blob
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                containerName:
                  type: string
                  example: your-container
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: File uploaded successfully
                  fileUrl:
                    type: string
                    example: https://youraccount.blob.core.windows.net/your-container/your-file.jpg
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /getData:
    get:
      summary: Fetch sample data
      operationId: fetchData
      description: Endpoint for retrieving data
      responses:
        '200':
          description: Data fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Data fetched successfully
                  data:
                    type: array
                    items:
                      type: string
                      example: Sample Data

  /createData:
    post:
      summary: Create new data entry
      operationId: createData
      description: Endpoint for creating a new data entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: New Entry
                description:
                  type: string
                  example: This is a new entry
      responses:
        '201':
          description: Data created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Data created successfully
                  id:
                    type: string
                    example: 12345
        '400':
          description: Invalid input
        '500':
          description: Internal server error

components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
