openapi: 3.0.0
info:
  title: Simple CRUD API
  description: API for managing items.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server

paths:
  /items:
    get:
      summary: Get all items
      responses:
        '200':
          description: A list of items.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
    post:
      summary: Create a new item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '201':
          description: Item created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'

  /items/{id}:
    get:
      summary: Get a specific item by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single item.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Item not found
    put:
      summary: Update an item by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '200':
          description: Item updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
    delete:
      summary: Delete an item by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Item deleted successfully.

components:
  schemas:
    Item:
      type: object
      required:
        - name
      properties:
        id:
          type: string
          example: '123'
        name:
          type: string
          example: 'Sample Item'
        description:
          type: string
          example: 'This is a sample item description.'
        price:
          type: number
          example: 19.99
        category:
          type: string
          example: 'Electronics'
