openapi: 3.0.0
info:
  title: AwsUpload
  version: 1.0.0
paths:
  /awsupload:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
        '402':
          description: Payment Required
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
    get:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
        '402':
          description: Payment Required
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
        '402':
          description: Payment Required
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
    delete:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
        '402':
          description: Payment Required
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
  /upload:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                type:
                  type: string
                format:
                  type: binary
      responses:
        '200':
          description: Successful response
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  description:
                    type: File Uploaded successfully
        '402':
          description: Payment Required
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
