openapi: 3.0.0
info:
  title: AWS File Upload API
  version: 1.0.0
  description: API for uploading files to AWS S3

paths:
  /upload:
    get:
      summary: Get all products
      operationId: getProducts
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Upload a file to AWS S3
      operationId: uploadFile
      isFileUpload: true
      uploadType: aws-s3
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                bucketName:
                  type: string
                  example: your-bucket
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: File uploaded successfully
                  fileUrl:
                    type: string
                    example: https://your-bucket.s3.amazonaws.com/your-file.jpg
        '400':
          description: Invalid input
        '500':
          description: Internal server error
  /products/{productId}:
    get:
      summary: Get a product by ID
      operationId: getProductById
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found

    put:
      summary: Update a product by ID
      operationId: updateProduct
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

    delete:
      summary: Delete a product by ID
      operationId: deleteProduct
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product deleted successfully
		  
components:
  schemas:
    Product:
      type: object
      required:
        - name
        - price
      properties:
        id:
          type: string
          example: "12345"
        name:
          type: string
          example: "Laptop"
        description:
          type: string
          example: "A powerful laptop"
        price:
          type: number
          example: 999.99
        category:
          type: string
          example: "Electronics"
